version: "3.8"

services:

  # The Sourcegraph server.
  server:
    image: sourcegraph/server:3.33.0
    ports:
      - "7080:7080"
      - "127.0.0.1:3370:3370"
    volumes:
      - ~/.sourcegraph/config:/etc/sourcegraph
      - ~/.sourcegraph/data:/var/opt/sourcegraph

  # Run Sourcegraph's "src" CLI tool to spin up a simple Git server. This is a neat and simple alternative compared to
  # running an entire code host like GitLab locally.
  #
  # Reference:
  #  - https://github.com/sourcegraph/src-cli
  #  - https://hub.docker.com/r/sourcegraph/src-cli
  src-serve-git:
    image: sourcegraph/src-cli:3.33.0
    volumes:
      # Bind mount (usually called "volumes") the directory on your computer that contains your Git repositories.
      # I put my repos in "~/repos", for example.
      - ~/repos:/repos
    command: serve-git /repos
